version: '3.8'


services:

  mongo:
    image: mongo:latest    
    ##command: --smallfiles
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_master_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express    
    environment:
      # ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASICAUTH_USERNAME}
      # ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASICAUTH_PASSWORD}
      # ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_MONGODB_ADMINUSERNAME}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${ME_MONGODB_ADMINUSERNAME}:${ME_MONGODB_ADMINPASSWORD}@mongo:27017/"
      VCAP_APP_PORT: 8881
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
    ports:
      - "8881:8881"

volumes:
  mongodb_master_data:

networks: 
    mongo-compose-network:
      driver: bridge